spring.application.name=6ThSem_Project


spring.datasource.url=jdbc:mysql://localhost:3306/Project6TH
spring.datasource.username=root
spring.datasource.password=Vik@7727

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret-key=cbdcdnnvgh87nbvhjj478nbccbvdcbmbjdkjsbhjb

logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG

# Use your API Key here (or better, as an environment variable)
spring.ai.openai.api-key= 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

# Specify the model you want to use
spring.ai.openai.chat.options.model=gpt-4o-mini

