spring.application.name=6ThSem_Project


spring.datasource.url=jdbc:mysql://localhost:3306/Project6TH
spring.datasource.username=root
spring.datasource.password=Vik@7727

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret-key=cbdcdnnvgh87nbvhjj478nbccbvdcbmbjdkjsbhjb

logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG

# Use your API Key here (or better, as an environment variable)
spring.ai.openai.api-key= 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

# Specify the model you want to use
spring.ai.openai.chat.options.model=gpt-4o-mini

