spring.application.name=6ThSem_Project


spring.datasource.url=jdbc:mysql://localhost:3306/Project6TH
spring.datasource.username=root
spring.datasource.password=Vik@7727

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret-key=cbdcdnnvgh87nbvhjj478nbccbvdcbmbjdkjsbhjb

logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG

# Use your API Key here (or better, as an environment variable)
spring.ai.openai.api-key= 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

# Specify the model you want to use
spring.ai.openai.chat.options.model=gpt-4o-mini

